import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],

  // Manual sidebar for the Physical AI Book
  physicalAISidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction'
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals and Robot Modeling',
      items: [
        {
          type: 'doc',
          id: 'module-1-ros2/lesson-1-1-ros2-architecture',
          label: 'Lesson 1.1: ROS 2 Architecture and Communication'
        },
        {
          type: 'doc',
          id: 'module-1-ros2/lesson-1-2-robot-modeling-urdf',
          label: 'Lesson 1.2: Robot Modeling with URDF'
        },
        {
          type: 'doc',
          id: 'module-1-ros2/lesson-1-3-robot-control-rclpy',
          label: 'Lesson 1.3: Robot Control with rclpy'
        }
      ]
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin Simulation and Physics',
      items: [
        {
          type: 'doc',
          id: 'module-2-simulation/lesson-2-1-gazebo-simulation',
          label: 'Lesson 2.1: Gazebo Simulation Fundamentals'
        },
        {
          type: 'doc',
          id: 'module-2-simulation/lesson-2-2-unity-digital-twin',
          label: 'Lesson 2.2: Unity Digital Twin Integration'
        },
        {
          type: 'doc',
          id: 'module-2-simulation/lesson-2-3-sensor-simulation',
          label: 'Lesson 2.3: Sensor Simulation and Physics'
        }
      ]
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac Ecosystem and Navigation',
      items: [
        {
          type: 'doc',
          id: 'module-3-isaac/lesson-3-1-isaac-sim-synthetic-data',
          label: 'Lesson 3.1: NVIDIA Isaac Sim and Synthetic Data'
        },
        {
          type: 'doc',
          id: 'module-3-isaac/lesson-3-2-isaac-ros-vslam',
          label: 'Lesson 3.2: Isaac ROS VSLAM Implementation'
        },
        {
          type: 'doc',
          id: 'module-3-isaac/lesson-3-3-nav2-navigation',
          label: 'Lesson 3.3: Nav2 Autonomous Navigation'
        }
      ]
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action Systems and Capstone',
      items: [
        {
          type: 'doc',
          id: 'module-4-vla/lesson-4-1-vision-language-integration',
          label: 'Lesson 4.1: Vision-Language Integration'
        },
        {
          type: 'doc',
          id: 'module-4-vla/lesson-4-2-llm-robot-planning',
          label: 'Lesson 4.2: LLM-Based Robot Planning'
        },
        {
          type: 'doc',
          id: 'module-4-vla/lesson-4-3-humanoid-autonomy-capstone',
          label: 'Lesson 4.3: Humanoid Autonomy Capstone'
        }
      ]
    }
  ]
};

export default sidebars;